### ISSUE TITLE
AUR Compile Issue

### ISSUE THREAD

**Issue by Angell1993** [luxtorpeda-dev/luxtorpeda#115]
### Linux Distribution

Manjaro 21.1.6 Pahvo

### Luxtorpeda Version

45.0.0.r320.5f2e835-2

### Bug description

Building luxtorpeda-git...
==> Making package: luxtorpeda-git 45.0.0.r320.5f2e835-2 (Fri 05 Nov 2021 15:42:20 CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating luxtorpeda git repo...
Fetching origin
  -> Found reproducible-build.patch
  -> Found size-optimisations.patch
==> Validating source files with sha256sums...
    luxtorpeda ... Skipped
    reproducible-build.patch ... Passed
    size-optimisations.patch ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of luxtorpeda git repo...
Cloning into 'luxtorpeda'...
done.
==> Starting prepare()...
patching file Makefile
Hunk #1 succeeded at 38 (offset 1 line).
patching file Cargo.toml
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
cargo build --release --locked
 Downloading crates ...
error: failed to download `bit-set v0.2.0`

Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/angel/.cargo/registry/src/github.com-1ecc6299db9ec823/bit-set-0.2.0/Cargo.toml`

Caused by:
  dependency (bit-vec) specified without providing a local path, Git repository, or version to use.
make: *** [Makefile:41: release] Error 101
==> ERROR: A failure occurred in build().
    Aborting...

### Steps To Reproduce

1. Find & Try to compile it from AUR..

### Expected Behavior

Hopefully it should compile..

### Additional Context

OS: Manjaro 21.1.6 Pahvo
Kernel: x86_64 Linux 5.14.10-1-MANJARO
DE: LXQt 0.17.0
WM: OpenBox

**Comment by d10sfan** [comment]
@Angell1993 

This error looks to be related to a cargo bug: https://github.com/rust-lang/cargo/issues/9885

Are you on the latest rust that arch provides?

**Comment by Angell1993** [comment]
I'm updating, every time Pamac tells me to, so I think so..

rust 1:1.55.0-1

**Comment by d10sfan** [comment]
@Angell1993 I've created a workaround that'll be in the next build: https://github.com/luxtorpeda-dev/luxtorpeda/pull/117

Look out for release 46, which should have this workaround. Also, whenever cargo/rust updates, that hopefully will also fix it.
