### ISSUE TITLE
Switch possition of B and A buttons

### ISSUE THREAD

**Issue by ToughGuyKunio** [luxtorpeda-dev/luxtorpeda#120]
### Feature Request

I think the position of B and A buttons in EGUI should be the same as on the Xbox or Steam Deck controllers.

### Solution

Switch position so that A is first and then B.

### Additional Context
A should still be "Ok" and B should still be "Cancel"

**Comment by d10sfan** [comment]
@ToughGuyKunio Are you talking about the physical position of the buttons in the UI? So that instead of it being Cancel, Ok, it would be Ok, Cancel?

**Comment by ToughGuyKunio** [comment]
@d10sfan Yes. Ok, cancel. A, B.

**Comment by d10sfan** [comment]
@ToughGuyKunio 

Did you test the PR build for the ps3 controller change?

**Comment by d10sfan** [comment]
https://github.com/luxtorpeda-dev/luxtorpeda/actions/runs/1433289553

**Comment by ToughGuyKunio** [comment]
> @ToughGuyKunio
> 
> Did you test the PR build for the ps3 controller change?

Not yet, I can do it tomorrow

**Comment by d10sfan** [comment]
@ToughGuyKunio Ok, let me know how that goes. If that works for you, I'll see about this change and the rest for a build soon.

**Comment by ToughGuyKunio** [comment]
@d10sfan tested now, worked perfectly!
![Screenshot_playstationbuttons](https://user-images.githubusercontent.com/12818876/140817504-8ca3e2e4-e659-4e2b-9fe7-5338df1f6201.jpg)

**Comment by d10sfan** [comment]
@ToughGuyKunio 

This is done in the PR, there's a build here if you want to try it out: https://github.com/luxtorpeda-dev/luxtorpeda/actions/runs/1437113221

**Comment by ToughGuyKunio** [comment]
@d10sfan Looks good
![Screenshot_okcancel](https://user-images.githubusercontent.com/12818876/140882414-5511aeae-a574-4dbf-9551-03508763d7e3.jpg)
