### ISSUE TITLE
Environment variable to hide the GUI when a default game is selected

### ISSUE THREAD

**Issue by Sterophonick** [luxtorpeda-dev/luxtorpeda#131]
### Feature Request

On Steam Deck (or in Gamescope, for that matter), after selecting a default engine for a game, the launcher window is a little bit annoying, especially when it's blown up to the entire screen.

### Solution

The solution would be a simple environment variable such as `LUX_SKIP_LAUNCHER=1` to skip the launcher window, making the decision easily reversible. This should only be done when a default engine is selected, however.

**Comment by d10sfan** [comment]
@Sterophonick 

Thanks for the suggestion. I've implemented this as part of version 51 - https://github.com/luxtorpeda-dev/luxtorpeda/pull/132

It should be live a few minutes after this comment as a release. Documentation on how to use it can be found here: https://github.com/luxtorpeda-dev/luxtorpeda#configuration (look for LUX_DISABLE_DEFAULT_CONFIRM)

As well, this release had a few package upgrades. If you could test and let me know how it goes, that'd be great. Also, if you have a steam deck, please let me know how the dialogs work after this build as well (like for picking an option when there isn't a default for example).

**Comment by Sterophonick** [comment]
Absolutely wonderful! Thank you so much! <3

I don't have a Steam Deck, unfortunately, so I can't help you there

**Comment by d10sfan** [comment]
> Absolutely wonderful! Thank you so much! <3
> 
> I don't have a Steam Deck, unfortunately, so I can't help you there

No worries, let me know if you run into any issues.

I do have one reserved and have a laptop that I use to test with gamescope.
