### ISSUE TITLE
Include versioning information on github builds

### ISSUE THREAD

**Issue by HunterKing** [luxtorpeda-dev/luxtorpeda#156]
### Feature Request

On builds via the GitHub releases page, no `version` or `version.txt` is included. This is helpful for end users to know what version they are using.

### Solution

Include `version.txt` on builds available via GitHub.

**Comment by d10sfan** [comment]
@HunterKing Thanks for the request, that's a great idea! I'll change it so that my PR builds have the commit hash in the version.txt, and then for an official release, it'll have the version number (like "55").

**Comment by HunterKing** [comment]
Thank you! It might be helpful to refer to Proton-GE, as they have been including versioning info in their releases for some time. Unsure if there is official Valve documentation on versioning of compatibility tools.

**Comment by d10sfan** [comment]
@HunterKing Thanks for the request, this is now in the new version 56 release.
