### ISSUE TITLE
UI scaling too small on Steam Deck desktop

### ISSUE THREAD

**Issue by parkerlreed** [luxtorpeda-dev/luxtorpeda#157]
### Linux Distribution

Steam OS 3.0

### Luxtorpeda Version

v55

### Bug description

With external monitors, scaling is almost too tiny to read.

![image](https://user-images.githubusercontent.com/841440/182467222-a3e5837c-f1e7-4982-9e48-f2f559d50934.png)

### Steps To Reproduce

1. Run luxtorpeda in desktop mode on Steam Deck

### Expected Behavior

Scaling suits the current display.

### Additional Context

From Discord @d10sfan 

>The window and dpi settings should scale with the resolution. It is disabled for the steam deck currently, because the screen itself (not using a monitor with it), the dpi that is reported makes the text size too big.

**Comment by d10sfan** [comment]
@parkerlreed 

I have a possible fix in the following build if you can try it out (in desktop and gaming mode). I'm still testing, but I think this should work.
[luxtorpeda.tar.xz.zip](https://github.com/luxtorpeda-dev/luxtorpeda/files/9256643/luxtorpeda.tar.xz.zip)

**Comment by d10sfan** [comment]
@parkerlreed Thanks for the report, this is now in the new version 56 release. Let me know how it goes for you.

**Comment by parkerlreed** [comment]
Yep all good! Thank you
