### ISSUE TITLE
Set recommended controller configuration for certain engines

### ISSUE THREAD

**Issue by neuromancer** [luxtorpeda-dev/luxtorpeda#190]
### Feature Request

Certain engines will need a specific gamepad/joystick configuration in order to be really playable.

### Solution

 Investigate if luxtorpeda can configure or at least, suggest a config for each engine.

**Comment by d10sfan** [comment]
@neuromancer Are you talking about steam configurations or in-game configurations?

There's already some games where the game engine data is setting a gamepad configuration, you can see those by the metadata. Is there any in particular that you're interested in?

**Comment by d10sfan** [comment]
For reference, the last time I messed around with it was this ticket: https://github.com/luxtorpeda-dev/packages/issues/529

You'll also see in the metadata (the json file in packages) where there's references to controller support and what's known/supported so far.

**Comment by neuromancer** [comment]
> Are you talking about steam configurations

Yes. In the particular case of wetlands, the steam controller with the gyroscope works great (moving the mouse with the trackpad is really slow), so perhaps could be nice to associated a particular config option with that.

**Comment by d10sfan** [comment]
Interesting, not sure if theres anything we can do to change steam controller configs, but could be worth looking into. Theres packages like this (https://github.com/meh/steamy/tree/master/vdf) that can read vdf files but would still need to determine where those are stored and how they could be changed,

**Comment by d10sfan** [comment]
Looks like the following could be used to get the steam user id:

```
STEAM_CLIENT_CONFIG_FILE = /home/d10sfan/.local/share/Steam/steam.cfg

STEAM_COMPAT_CLIENT_INSTALL_PATH = /home/d10sfan/.local/share/Steam

SteamUser = d10sfan

/home/d10sfan/.local/share/Steam/config/loginusers.vdf

= 
"users"
{
	"76561197990646384"
	{
		"AccountName"		"d10sfan"
		"PersonaName"		"d10sfan"
		"RememberPassword"		"1"
		"WantsOfflineMode"		"0"
		"SkipOfflineModeWarning"		"0"
		"AllowAutoLogin"		"1"
		"mostrecent"		"1"
		"Timestamp"		"1694443004"
	}
}
```

Once the 76561197990646384 is found (which is a steamid64), it can be converted to a steamid3. 

Then if the folder the game lives in has a steam_input_template.vdf file, copy it to /home/d10sfan/.steam/steam/userdata/30380656/241100/remote/controller_config/1148590/, replacing the user id and the app id.

**Comment by d10sfan** [comment]
Implemented this in https://github.com/luxtorpeda-dev/luxtorpeda/pull/242

Steam input templates can be provided in the game directory and then they'll be imported. Some more details can be seen here about how to create the template - https://github.com/luxtorpeda-dev/packages/blob/master/docs/Creating_a_Package.md#steam-input-templates
