### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [luxtorpeda-dev/luxtorpeda#195]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by d10sfan** [comment]
Seems interesting to spam this to over 500 repos for a feature that is currently in beta.

I appreciate the notice and have enabled the feature. Feel free to report with that tool, and I will investigate when I can. Note that any communication from this tool I will decide to make public if necessary.
