### ISSUE TITLE
Steam Deck Virtual Keyboard not working in game

### ISSUE THREAD

**Issue by XLRUUU** [luxtorpeda-dev/luxtorpeda#209]
### Linux Distribution

SteamOS 3.0

### Luxtorpeda Version

v64

### Bug description

Hello,

I have a problem using the Steam Deck virtual keyboard in game,

When in game, typing on the keyboard doesn't work, for example, writing save names, chat or using the game console.

I've got this issue in multiple games like Doom 3 (using the Dhewm3 source port), Doom (using GZDoom, QZDL) but it seems to work in the QZDL interface before launching the game.

I'm not sure if this a Luxtorpeda issue or a SteamOS one.

Thanks.

### Steps To Reproduce

1 Open a game that works with Luxtorpeda
2 Use any text input with the SteamOS virtual keyboard.

### Expected Behavior

The keyboard should "write" the text in the text fields.

**Comment by d10sfan** [comment]
@XLRUUU Does the same thing happen in desktop mode for you as well?

Nothing luxtorpeda is doing should affect the keyboard, so that's interesting.

And what do you mean by typing not working? Are  you able to launch the virtual keyboard and type but it's not actual being outputted to the screen/text field? Or something else?

If you have a usb or bluetooth keyboard, does typing in that work?

**Comment by XLRUUU** [comment]
Yes, it happens on desktop mode too.

It's probable that the problem is on the SteamOS side. Maybe because there is multiple process running when using Luxtorpeda, the Luxtorpeda launcher is still listed in the Switch Windows menu on the Steam Deck interface "overlay" menu. And the Luxtorpeda window is still opened when the game is running on desktop mode.

This issue doesn't happen when playing the same game without Luxtorpeda (in Doom 3 for example)

Yes, the keyboard opens but I can't write text, and I can remove text with backspace, it's really strange. And the issue isn't limited to the virtual keyboard, I have a custom layout on my Deck that use keys when I press the Deck buttons, so I binded wasd to the left joystick, the input is recognized in game, I can walk and do every action with the keybinds, but when typing text, the keybinds doesn't write anything too. I'm sorry if it's too convulted to understand.

No I don't have any keyboard that I can connect to my Deck.

I will try to report this bug to Valve too.

Thanks.

**Comment by d10sfan** [comment]
@XLRUUU If you can try, if you go into the steamos window selector (when in gaming mode), you can stop the luxtorpeda process after the game is running, and the game should keep going. Let me know if that helps with the keyboard issues at all.

**Comment by d10sfan** [comment]
Also, by not using luxtorpeda, do you mean using proton for those games, like doom?

**Comment by XLRUUU** [comment]
I tried closing the Luxtorpeda window but it didn't change anything.

Yes, I launch Doom 3 with the default compatibility tool (proton).

I hope I don't waste your time if the issue is on the SteamOS / Virtual Keyboard side.

Thanks.

**Comment by d10sfan** [comment]
I can replicate the problem on my steam deck and gzdoom. I'd like to try and find a solution but not sure what the actual issue is. 

Another interesting data point is that the lux client can accept text input from the keyboard. For example, ut2004 requires you to put in the cd key in the godot UI, and that works fine. That game also works for in-game text (like typing in your username in the player box) with the on-screen keyboard.

So it seems to be something about certain games possibly.

**Comment by XLRUUU** [comment]
I've tried playing Jedi Outcast with Luxtorpeda and the keyboard works in this game, strange.

And when launching Doom with QZDL, I can actually write things too, in the various text inputs of the program, but when launching the game, the keyboard issue happens.

Iirc I could write in GZDoom when I played it month ago but not Doom 3, but I'm not really sure now.

When playing the flatpak version of GZDoom (from the Discovery app) the keyboard works too, but I don't know if the flatpak is on the same version.

**Comment by d10sfan** [comment]
are you using gzdoom from flatpak as a non-steam game or playing directly? If you're playing directly, can you try adding it as a non-steam game and seeing if the keyboard still works?

**Comment by XLRUUU** [comment]
I've added it as a non Steam game yes, and in gaming mode.

**Comment by d10sfan** [comment]
Interesting I'm guessing that the flatpak has some differences in the libraries used, as I'm not doing anything special on the build process in terms of custom flags.

Does an older version of luxtorpeda like 59 have the same behavior or does the keyboard work there with gzdoom? https://github.com/luxtorpeda-dev/luxtorpeda/releases/tag/v59

**Comment by XLRUUU** [comment]
Using ProtonUpQt I've downloaded v59 and v49 and it's the same

**Comment by d10sfan** [comment]
Ah ok good to know, was thinking it may have been something to do with the new Godot ui

**Comment by d10sfan** [comment]
This is re-producible with half life 2 and trying to use the console, so seems to be something wrong with the steam deck keyboard. Not sure why it works in some cases and not others, possibly due to differences in the way the engines handle input.

**Comment by XLRUUU** [comment]
Same thing here, can't use the console in Half-Life 2, the issue is clearly on the SteamOS side.

**Comment by XLRUUU** [comment]
Nevermind, I can write in the Half-Life 2 console, but it seems that the Half-life 2 new Deck UI makes the console harder to "focus", so it's maybe not related then.

I've attached a screenshot.

![downloadfile(2)](https://github.com/luxtorpeda-dev/luxtorpeda/assets/135256777/eb0ecfca-a6fb-4403-a24a-7ce9b3099134)

**Comment by d10sfan** [comment]
strange, it wasn't working for me, i could tell that the text field was focused because I wasn't able to type but I could hit the return key.

**Comment by XLRUUU** [comment]
Oh I know why, the keyboard works when I'm using Proton, but when using the native Linux build of Half-Life 2, the keyboard doesn't.

**Comment by d10sfan** [comment]
Ah I see, yeah that points to some issue with native linux gaming and the steam deck keyboard.

**Comment by XLRUUU** [comment]
Yeah, I thought that the Linux build would work better than using Proton lol.

I've posted the bug report in the Steam Deck forum, but there's so many posts, I don't know if Valve will see it.

**Comment by d10sfan** [comment]
Going ahead and tagging this as not our bug for now but will leave it open as a reminder as hopefully this will be resolved. I did post a ticket about the half life 2 example so maybe that'll cause a fix

**Comment by XLRUUU** [comment]
Ok, thanks for everything.

**Comment by JoshuaFern** [comment]
Try reporting in https://github.com/ValveSoftware/SteamOS/issues

**Comment by d10sfan** [comment]
https://github.com/ValveSoftware/SteamOS/issues/1053
