### ISSUE TITLE
Launching Doom 3 causes "no directory" error

### ISSUE THREAD

**Issue by hfc2x** [luxtorpeda-dev/luxtorpeda#225]
### Linux Distribution

Fedora 38

### Luxtorpeda Version

65.1.1

### Bug description

Launching [Doom 3](https://steamdb.info/app/9050/info/) is impossible, due to Luxtorpeda somehow not detecting the game being installed. See picture:

![2023-08-04_16-23](https://github.com/luxtorpeda-dev/luxtorpeda/assets/8249996/26da0f8e-091f-453b-9148-f2279f03e043)

This may be related to #223, because I deleted the Doom 3 folder manually, before uninstalling from Steam, and then reinstalling.

### Steps To Reproduce

1. Delete Doom 3 folder manually
2. Uninstall game from Steam
3. Reinstall
4. Luxtorpeda gives "no such file or directory" error.

### Expected Behavior

Luxtorpeda should try and download dhewm3, and/or launch the game.

### Additional Context

Was trying to test a possible configuration to help enable Steam Cloud compatibility, but I had an unrelated error. Now the game can't launch and Luxtorpeda refuses to download dhewm3.

**Comment by d10sfan** [comment]
Can you run steam in a terminal window and the paste the log results in a file and attach it here?

If you manually delete, it should detect that the binary does not exist and extract anyways, so curious what may be going on there.

**Comment by hfc2x** [comment]
I launched Luxtorpeda with logging enabled, and it gives this, despite dhewm3 not being downloaded yet:

```
23:33:19 [INFO] setup_logging with write success
23:33:19 [INFO] config_file_path exists, reading
23:33:19 [INFO] config_file_path exists, reading
23:33:19 [INFO] update_packages_json. found hash: 028febd96948a4baed45bb3bdff2bf29b62165b3d8a1bd90407fec04d19e8ba7
23:33:19 [INFO] update_packages_json. found hash and remote hash: 028febd96948a4baed45bb3bdff2bf29b62165b3d8a1bd90407fec04d19e8ba7 028febd96948a4baed45bb3bdff2bf29b62165b3d8a1bd90407fec04d19e8ba7
23:33:19 [INFO] packages_json_file exists, reading
23:33:19 [INFO] user_packages_file not found
23:33:19 [INFO] dhewm3-common-49.tar.xz found in cache (skip)
23:33:19 [INFO] packages_json_file exists, reading
23:33:19 [INFO] user_packages_file not found
23:33:19 [INFO] dhewm3-common-49.tar.xz found in cache (skip)
23:33:19 [INFO] Downloads is empty
23:33:19 [INFO] packages_json_file exists, reading
23:33:19 [INFO] user_packages_file not found
23:33:19 [INFO] json:
23:33:19 [INFO] Game { game_name: "DOOM 3", engine_name: "dhewm3", command: Some("./run-dhewm3.sh"), command_args: [], download_config: None, cloud_not_available: false, cloud_supported: false, cloud_available: true, cloud_issue: false, download: [DownloadItem { name: "dhewm3", url: "https://github.com/luxtorpeda-dev/packages/releases/download/dhewm3-49/", file: "dhewm3-common-49.tar.xz", cache_by_name: true }], app_id: "9050", choices: None, notices: None, controller_steam_default: false, use_original_command_directory: false, app_ids_deps: None, setup: None, commands: None }
23:33:19 [INFO] config_file_path exists, reading
23:33:19 [INFO] hash_check_install is enabled, checking for dhewm3
23:33:19 [INFO] dhewm3.hash has been found, checking hash against file
23:33:19 [INFO] cached hash is 6f3234acbce6c512be98c4f5fd0a36fd7a91cf0433146eb09fa90c6ef22f6a81; install file hash is 6f3234acbce6c512be98c4f5fd0a36fd7a91cf0433146eb09fa90c6ef22f6a81
23:33:19 [INFO] hash for dhewm3 is same, skipping install
23:33:19 [INFO] run: "./run-dhewm3.sh" with args: [] ["+set", "fs_savepath", "../Doom 3"]
23:33:19 [ERROR] command::run_wrapper err: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

Seems to think dhewm3 is already downloaded, and somehow checks and passes the hashes, despite none of the files existing..

Steam logs much of the same as Luxtorpeda does, but adds these lines at the end:
```
23:33:19 [INFO] run: "./run-dhewm3.sh" with args: [] ["+set", "fs_savepath", "../Doom 3"]
23:33:19 [ERROR] command::run_wrapper err: Os { code: 2, kind: NotFound, message: "No such file or directory" }
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
     at: cleanup (core/object.cpp:2070)
ERROR: Resources still in use at exit (run with --verbose for details).
   at: clear (core/resource.cpp:417)
Uploaded AppInterfaceStats to Steam
```

**Comment by d10sfan** [comment]
If you open your doom 3 install folder, is there a run-dhewm3.sh file? If so try to delete it and try again

**Comment by hfc2x** [comment]
No, there's nothing in the folder. Here's what I do:

1. Go into the Doom 3 install folder
2. Delete _every file_, including the `run-dhewm3.sh` file (yes, everything)
3. Go to Steam, and uninstall the game
4. Reinstall the game in the same folder as before
5. Launch (having set the forced compatibility through Luxtorpeda)
6. Error from the screenshot in the first post, with log suggesting all files passed the hash checks successfully

I think I'm just as confused as you are. I have no idea what files are being hash-checked here.

**Comment by d10sfan** [comment]
Strange it should be checking for that file to exist to extract ignoring the hash check. You should be able to delete the ~/.cache/luxtorpeda folder and thatll clear everything

**Comment by d10sfan** [comment]
The steam uninstall normally won't delete the lux files that are put there unless you remove them manually which is why I was thinking down that path

**Comment by hfc2x** [comment]
> Strange it should be checking for that file to exist to extract ignoring the hash check. You should be able to delete the ~/.cache/luxtorpeda folder and thatll clear everything

Yeah, deleting the files inside `/home/[user]/.cache/luxtorpeda/9050/` actually did the trick. I'm not sure if this issue should be closed?

**Comment by d10sfan** [comment]
Can you double check the version you're on? One of the logs seems to be missing this part: game_command_file_found

Which was added by the latest version and is related to the fix for this issue

**Comment by hfc2x** [comment]
Uhhh.. I didn't notice, but I was in 65.1.0. I updated it now to latest.

**Comment by d10sfan** [comment]
Great glad it's working on the latest version
