### ISSUE TITLE
Update GZDoom Version

### ISSUE THREAD

**Issue by nickxcom** [luxtorpeda-dev/luxtorpeda#226]
### Feature Request

I would love a way to update the included GZDoom Version. The included is out of date and missing features/ had some odd sound handling issues not currently present.

### Solution

I would love to either update the version myself or maybe see a bump to the included version?

**Comment by nickxcom** [comment]
Realized my info might be out of date. I will have to track down the weird issues elsewhere as it actually DOES appear to be up to date

**Comment by d10sfan** [comment]
Not sure what you mean on this one, you can see the version on https://luxtorpeda-dev.github.io/ and it's the latest version.

Also, package-related issues for future reference should be put into the packages repo, not this one.
