### ISSUE TITLE
Missing Loading Bar on Downloading Games

### ISSUE THREAD

**Issue by JoshuaFern** [luxtorpeda-dev/luxtorpeda#24]
**Describe the bug**
Luxtorpeda used to have a loading bar when downloading game engines/content. It doesn't seem to occur anymore.

**Expected behaviour**
A functional loading bar appears in the native steam dialog representing the download progress.

**Additional context**
Luxtorpeda-9, Steam July 8 2020 build

**Comment by d10sfan** [comment]
Fixed in luxtorpeda 10. Let me know if you run into further issues.
