### ISSUE TITLE
Old luxtorpeda repository is confusing users

### ISSUE THREAD

**Issue by neuromancer** [luxtorpeda-dev/luxtorpeda#249]
### Linux Distribution

Any

### Luxtorpeda Version

Any

### Bug description

Users are still posting issues in the old [luxtorpeda repository](https://github.com/dreamer/luxtorpeda), which is not maintained any more. Perhaps @dreamer could archive the repository if they are not doing active development any more?

### Steps To Reproduce

NA

### Expected Behavior

 NA

**Comment by d10sfan** [comment]
True, it may be worthwhile to post this in dreamer's repository if you'd like. It would be beneficial to have more of a notice that that repo isn't being maintained and isn't related to the project you see around.
