### ISSUE TITLE
Engine not showing when launching game (UT2004, non steam game)

### ISSUE THREAD

**Issue by rreettrrogg** [luxtorpeda-dev/luxtorpeda#250]
### Linux Distribution

Steam OS 3.4.10

### Luxtorpeda Version

67.0.0

### Bug description

I'm honestly not sure if I'm doing something wrong or not. I'm new to Linux, SteamOS (and Github).
My problem is :
I installed Unreal Tournament 2004 through Lutris and when I launch it through Lutris, it launches fine. 
I wanted to have an easy and quick access to the game in steam OS, with banner, pic and everything. 
I added the UT2004.exe to Steam as a non Steam Game then used ProtonUp-Qt to install Luxtorpeda and when into Steam to force it as compatibility tool. 
When I launch UT2004 through steam OS I get prompted to choose an engine in a Luxtorpeda window but the ut2004 engine is not in the list. I only got 11 of them, from ScummVM to DREAMM, including Godot, all the RetroArchs and so on. All I can do is hit OK or Cancel or Toggle Default. 
Tried reinstalling everything but to no avail. 
Sorry if I'm just an idiot or asking the question in the wrong place. I looked online a lot and can't seem to find an answer. Looked at a few videos too but the right engine seems to magically download for everyone else. 

### Steps To Reproduce

I installed Unreal Tournament 2004 through Lutris and when I launch it through Lutris, it launches fine. 
I wanted to have an easy and quick access to the game in steam OS, with banner, pic and everything. 
I added the UT2004.exe to Steam as a non Steam Game then used ProtonUp-Qt to install Luxtorpeda and when into Steam to force it as compatibility tool. 
When I launch UT2004 through steam OS I get prompted to choose an engine in a Luxtorpeda window but the ut2004 engine is not in the list. I only got 11 of them, from ScummVM to DREAMM, including Godot, all the RetroArchs and so on. All I can do is hit OK or Cancel or Toggle Default. 
Tried reinstalling everything but to no avail. 

### Expected Behavior

Right engine (ut2004) downloads when launching UT2004.exe. and is added to the list of engines.

**Comment by d10sfan** [comment]
This is because lux is expecting steam games, non steam games aren't normally supported.

Lux uses the app id to determine which game it should be launching and the non steam stuff does not match 

You could try overriding the SteamAppId env variable in the launch options or use the custom engine metadata feature https://github.com/luxtorpeda-dev/luxtorpeda#user-packages-override

Either of those should work to support that, let me know how that goes.
