### ISSUE TITLE
Descent Freespace FS1 Engine Option (the non FS2Open one) gives error

### ISSUE THREAD

**Issue by Arkaium** [luxtorpeda-dev/luxtorpeda#256]
### Linux Distribution

Steam Deck 3.5.7

### Luxtorpeda Version

Latest as of 12/1/2023

### Bug description

Hi, I continue to love this compatibility layer, thank you!

I used to be able to get into Descent Freespace using the “Freespace” option (I don’t like how “Freespace port using FS2Open has a garish starfield background) but when I tried tonight on my new OLED Steam Deck I just set up, I get an error: “numeric field was not a number: when getting cksum for VPVP”

Appreciate your help!

### Steps To Reproduce

Trying to run Descent Freespace using the “Freespace” option

### Expected Behavior

The game used to run, I can’t remember as of which Luxtorpeda, but just months ago.

**Comment by d10sfan** [comment]
Thanks for the issue I'll work on replicating it when I have a chance

**Comment by d10sfan** [comment]
I've released a fix that'll be out once this action is complete - https://github.com/luxtorpeda-dev/luxtorpeda/actions/runs/7071067577 as 67.1.2

Let me know how that goes for you, it should fix the issue and let you play the game.

**Comment by Arkaium** [comment]
You’re amazing, thank you. Big studios don’t give this kind of fast support, and this is just a fun hobby for you (I hope it’s fun that is).I also ran into an issue with Unreal Gold (both 32 and 64 bit), I’ll create a bug for that as well, just needed to charge my battery so I can get the error report verbatim to add to GitHub.Hope you have a great weekend and thank you again so much for maintaining this wonderful project.Sent from my iPhoneOn Dec 2, 2023, at 7:28 AM, d10sfan ***@***.***> wrote:﻿
I've released a fix that'll be out once this action is complete - https://github.com/luxtorpeda-dev/luxtorpeda/actions/runs/7071067577 as 67.1.2
Let me know how that goes for you, it should fix the issue and let you play the game.

**Comment by d10sfan** [comment]
Thank you and glad it worked well!
