### ISSUE TITLE
List of supported games no longer available

### ISSUE THREAD

**Issue by Po11da** [luxtorpeda-dev/luxtorpeda#307]
Readme claims that full list of supported titles is available under https://www.luxtorpeda.org, but this is no longer the case. This URL redirects to current Luxtorpeda page at https://luxtorpeda-dev.github.io/, but this website only shows readme from the repository. Preferably, the list of supported titles should be recreated and links updated. If this task can't be easily accomplished, readme and web page should be updated to reflect current state.

**Comment by d10sfan** [comment]
It's there when you click on the packages button or https://luxtorpeda.org/packages

The header buttons I've made the colors different to make it a bit easier to see

![image](https://github.com/luxtorpeda-dev/luxtorpeda/assets/4337981/cc159f7a-2d37-4261-b311-8102acc9f1b7)

Clicking on one of those will take you to the other page. I've also updated the links to make it more obvious which ones are which.

Hope that helps
