### ISSUE TITLE
Games won't start all i get is godot window

### ISSUE THREAD

**Issue by BigCojones** [luxtorpeda-dev/luxtorpeda#324]
### Linux Distribution

Zorin lite 16.3

### Luxtorpeda Version

68.3.0

### Bug description

Trying to run games with luxtorpeda only gives me a "godot interface" with "toggle default" and "ok" options which are greyed out and "cancel" which i can use. So basically nothing will run.
![luxtorpedagodot](https://github.com/luxtorpeda-dev/luxtorpeda/assets/11190371/34e9c046-5732-4b43-bc6c-dcd8043bd8ab)
It responds to a controller, but doesn't help

Maybe some others have this same issue, so good to bring up imho. I tired arx fatalis, amnesia DD and rtcw. 

### Steps To Reproduce

Just trying to run games

### Expected Behavior

Games would start

### Additional Context

I don't know if it has something to do that I don't have a vk capable graphics card. I saw rcw installed some dxvk stuff before trying to run. But all of this should run with just opengl.

### Relevant log output

```shell
I don't know how to do this
```

**Comment by d10sfan** [comment]
Not sure but I don't think Godot has a vulkan dependency. Can you start steam in a terminal window, and then try launching a game? That'll output luxtorpeda's logs to that terminal and then if you could paste that into a file and upload it here, that'll help diagnose the problem.

**Comment by BigCojones** [comment]
Can't seem to paste text files, so just pasting here...

$ steam
tid(56461) burning pthread_key_t == 0 so we never use it
[2024-04-05 17:52:56] Startup - updater built Mar  6 2024 20:27:25
[2024-04-05 17:52:56] Startup - Steam Client launched with: '/home/jones/.steam/debian-installation/ubuntu12_32/steam' '-nominidumps' '-nobreakpad'
minidumps folder is set to /tmp/dumps
[2024-04-05 17:52:56] Using the following download hosts for Public, Realm steamglobal
[2024-04-05 17:52:56] 1. https://client-update.akamai.steamstatic.com, /, Realm 'steamglobal', weight was 1000, source = 'update_hosts_cached.vdf'
[2024-04-05 17:52:56] 2. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'update_hosts_cached.vdf'
[2024-04-05 17:52:56] 3. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2024-04-05 17:52:56] Verifying installation...
[2024-04-05 17:52:56] Verification complete
UpdateUI: skip show logo
Steam logging initialized: directory: /home/jones/.steam/debian-installation/logs

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf496d370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf496bcc0
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
ignoring iscriptevaluator.exe
chdir "/home/jones/.steam/debian-installation/steamapps/common/Arx Fatalis"
LD_PRELOAD found with /tmp/pressure-vessel-libs-0CZ0L2/${LIB}/gameoverlayrenderer.so
Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org
Vulkan API 1.1.182 - Forward+ - Using Vulkan Device #0: Unknown - llvmpipe (LLVM 12.0.0, 128 bits)
 
[2024-04-05 17:55:00] Background update loop checking for update. . .
[2024-04-05 17:55:00] Checking for available updates...
[2024-04-05 17:55:00] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12?t=642170016
[2024-04-05 17:55:00] Manifest download: send request
[2024-04-05 17:55:00] Manifest download: waiting for download to finish
[2024-04-05 17:55:00] Manifest download: finished
[2024-04-05 17:55:00] Download skipped: /steam_client_ubuntu12?t=642170016 version 1709846872, installed version 1709846872, existing pending version 0
[2024-04-05 17:55:00] Nothing to do

**Comment by d10sfan** [comment]
Ah I see, I forgot about forward+ being vulkan-based. It looks like it's using software rendering which may be why it isn't loading properly.

Can you try downloading the following version of lux and extract it in the proper steam compatibility tools area (on top of the one already there), and see if that helps? This switches godot to its compat mode, which should use opengl instead.

[luxtorpeda.tar.xz.zip](https://github.com/luxtorpeda-dev/luxtorpeda/files/14887056/luxtorpeda.tar.xz.zip)

If this dosen't work, please provide another log file.

**Comment by BigCojones** [comment]
You propably mean /.steam/debian-installation/compatibilitytools.d/luxtorpeda/ right?

Just extract or do i need to install it?

**Comment by d10sfan** [comment]
If that is your path then yes, you'll want to extract the .tar.xz inside the zip into that folder so it replaces the files there

**Comment by BigCojones** [comment]
It seems to be working fine afaik, but my laptop is even older and only supports opengl 2.1,  which is a big reason why i'm trying to get this to work. :D

![21](https://github.com/luxtorpeda-dev/luxtorpeda/assets/11190371/69d38575-1ebf-449f-a5de-9510ee51d743)

here's the log:

XRRGetOutputInfo Workaround: initialized with override: 0 real: 0xf49d3370
XRRGetCrtcInfo Workaround: initialized with override: 0 real: 0xf49d1cc0
bus_name=com.steampowered.PressureVessel.LaunchAlongsideSteam
chdir "/home/jones/.steam/debian-installation/steamapps/common/Jagged Alliance 2 Gold"
LD_PRELOAD found with /tmp/pressure-vessel-libs-Y1CRL2/${LIB}/gameoverlayrenderer.so
Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org

Seemingly the lowest godot will go is OpenGL 3. You may want to add this requirement as a note, because many of the supported engines do not require 3.3.

So unless you are willing to rewrite your entire app, no steam game times for me on this laptop. :D

Which is perfectly fine, I can still use the native engines outside of steam. Would have been convenient tho :)

**Comment by d10sfan** [comment]
Ah ok yeah, that's dependent on the minimum opengl version available that Godot supports.

Glad it sounds like that fixed it for your other machine. I'll make a new release shortly with that fix in it, so it'll generally available. If Godot ends up expanding the compatibility to include the older opengl, then I'll look into that as well.
