### ISSUE TITLE
Morrowind on OpenMW via Luxtorpeda is no longer working on Steam Deck

### ISSUE THREAD

**Issue by astradamus** [luxtorpeda-dev/luxtorpeda#337]
### Linux Distribution

SteamOS

### Luxtorpeda Version

v68.4.0

### Bug description

Every presented option (Open MW with/without launcher and with/without shaders) fails to launch, spitting you back out to the steam Morrowind page.

This was perfectly functional for me in the past, but it has been over a year since then, so I can't say exactly when this started.

### Steps To Reproduce

Assign Luxtorpeda as compat option for Morrowind. Launch.
Luxtorpeda starts up fine and presents the options for starting OpenMW with/without launcher and with/without shaders.
Every single option fails to launch.

### Expected Behavior

I've used this in the past and all the options were functional and the game was playable.

### Additional Context

I am on an OLED deck running latest version of SteamOS.

**Comment by astradamus** [comment]
I believe Luxtorpeda uses OpenMW 0.45.0?

I manually installed OpenMW 0.48.0 and hooked it to the Morrowind steam app and that works fine. So I'm assuming 0.45.0 is no longer compatible with SteamOS for some reason? 🤔

**Comment by d10sfan** [comment]
Openmw 0.48.0 is used for lux. Where do you see 0.45? 

Are you sure you're on the latest version? How did you download lux?

**Comment by astradamus** [comment]
Okay, figured some things out. I saw 0.45.0 here, but upon closer inspection I'm not even sure how I got to that page as it looks like it might just be some random person's fork.
https://github.com/dreamer/luxtorpeda/?tab=readme-ov-file#supported-titles

I completely deleted my Morrowind folder, installed fresh, and from there OpenMW worked fine via Luxtorpeda. This was the same folder I ran it out of in the past, so there must've been something left over from the previous OpenMW version or something.

I suppose that's still worth knowing about: updates to either OpenMW or Luxtorpeda are breaking the install and require a fresh install? 🤔

**Comment by d10sfan** [comment]
Ah yeah that's the old version of lux, the one you're on (in this issue) is the up-to-date version.

And nice, glad it's working now! Normally these updates shouldn't pose a problem, although if it was old enough (like from the dreamer version), it's possible something went wrong there. IF you find something like this again, feel free to create an issue with some logs so can diagnose it.
