### ISSUE TITLE
store updated package.json in ~/.cache/luxtorpeda instead of tools dir.

### ISSUE THREAD

**Issue by ZeroPointEnergy** [luxtorpeda-dev/luxtorpeda#41]
Hello. I'm in the process of packaging this software for the Gentoo user repository (GURU).

The package installs luxtorpeda to `/usr/share/steam/compatibilitytools.d/luxtorpeda/` where it is available for all users. However, if the user starts a game with luxtorpeda it tries to download the `package.json` file to `/usr/share/steam/compatibilitytools.d/luxtorpeda/` which is read-only for the user.

I see that I can disable the update in the `config.json` and just ship a static version of the `packages.json` file. But it would be nice if the user could get the newest version of the file as it probably gets updated between luxtorpeda releases.

A solution that enables the user to get the newest `packages.json` would be to change the download directory of packages.json from the tools directory to a user writable directory like `~/.cache/luxtorpeda`.

**Comment by d10sfan** [comment]
I've implemented this in luxtorpeda-dev 21, so that it'll get stored in the cache directory.
