### ISSUE TITLE
When I uninstall a game with multiple engines "Pick the engine below" is prompted

### ISSUE THREAD

**Issue by NerosTie** [luxtorpeda-dev/luxtorpeda#47]
**Describe the bug**
As the title says, when I want to uninstall a game with multiple engines, like Caesar III, during the process the window "Pick the engine below" is prompted. I click on "Cancel" then the game is uninstalled. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Install a game with multiple engines like Caesar III
2. Uninstall the game

**Expected behaviour**
The window "Pick the engine below" shouldn't be prompted when uninstalling a game.

**Screenshots**
![Screenshot_20210116_232630](https://user-images.githubusercontent.com/4572452/104824537-dc35ad80-5852-11eb-841f-fe4462b33c9b.png)

**Comment by d10sfan** [comment]
Thanks for the report, looks like an issue with the engine selector on the uninstall state. I'll look at what information the client gets from steam when this occurs.

**Comment by d10sfan** [comment]
@NerosTie 

I created a ticket with Valve's tracker here: https://github.com/ValveSoftware/steam-for-linux/issues/7622

From what I could tell, the luxtorpeda-dev client isn't getting anything different between a normal run and an uninstall. Hopefully that ticket will show something I missed or if they could possibly add that capability.

**Comment by d10sfan** [comment]
Closing this for now. Will re-open if there's any further activity from Valve.

**Comment by d10sfan** [comment]
I also looked to see if the uninstall process would delete the files before launching the client, but that does not appear to be the case. Because of that, I see no way of detecting this, unless we get help from Valve.

I'm going to close this for now, until there's more movement on this. I'll also add this to the known issues list

**Comment by d10sfan** [comment]
@NerosTie I've released 26 (https://github.com/luxtorpeda-dev/luxtorpeda/commit/86b2d29ae61b4dea45de1d27890694502eff84f0) that fixes this issue. luxtorpeda now parses the vdf file to determine if it's an uninstall or not. If it is, luxtorpeda will just exit.
