### ISSUE TITLE
Set default engine

### ISSUE THREAD

**Issue by PopeRigby** [luxtorpeda-dev/luxtorpeda#53]
**Is your feature request related to a problem? Please describe.**
For most games, I don't want to be asked every time if I want to use a certain engine, I just want to pick one and have Luxtorpeda use it every time I launch the game.

**Describe the solution you'd like**
Have a checkbox in the engine selection dialogue that says something like "Make this your default engine?" To revert this, you could either hold down a key while the game is launching to have the selector popup again, or maybe delete a file.

**Comment by d10sfan** [comment]
Possibly use zenity form: https://askubuntu.com/questions/822745/zenity-list-in-forms-dialog-is-not-viewable

Look into either detecting shift key or add docs as to where to delete file.

**Comment by d10sfan** [comment]
Added support for this in https://github.com/luxtorpeda-dev/luxtorpeda/pull/56

This adds an extra zenity prompt to ask for the default. Zenity does not support a checkbox in a form, and so this was the next best option. A file (which is listed in the README) can be deleted to restore the engine choice dialog. This will be version 24.
