### ISSUE TITLE
Add Luxtorpeda to Flathub

### ISSUE THREAD

**Issue by AsciiWolf** [luxtorpeda-dev/luxtorpeda#54]
Please, consider submitting Luxtorpeda to Flathub as a Steam CompatibilityTool extension. There [is already](https://github.com/gasinvein/flatpak-apps-staging/tree/com.valvesoftware.Steam.CompatibilityTool.Luxtorpeda/beta) a Flatpak manifest file for Luxtorpeda, it just needs to be updated.

See this ticket for more information: https://github.com/flathub/com.valvesoftware.Steam/issues/394

**Comment by d10sfan** [comment]
Thanks for the information. I added a comment in that ticket to start a dialog there. I'll close this for now, unless this one ends up being needed again.

**Comment by barfin** [comment]
> Thanks for the information. I added a comment in that ticket to start a dialog there. I'll close this for now, unless this one ends up being needed again.

any news on this? I'd love to use it from flathub like i use boxtron

**Comment by d10sfan** [comment]
@barfin What benefit do you get from flatpak for this, versus using it as is? lux-dev will work under flatpak steam as far as I an aware.

**Comment by barfin** [comment]
> @barfin What benefit do you get from flatpak for this, versus using it as is? lux-dev will work under flatpak steam as far as I an aware.

no don't get me wrong, it works just fine but flatpak is just more convenient and easier to install and stay updated
if someone installs it using ProtonUp-Qt or install it manually then they'll have to constantly check the github page or ProtonUp-Qt program to know that there is an update or something

**Comment by d10sfan** [comment]
Ah ok, I haven't had any interest in maintaining a flatpak for lux myself, but I'm not opposed if someone wants to take up that maintenance.

**Comment by d10sfan** [comment]
I've also thought about making some sort of internal updater which could also be another solution
