### ISSUE TITLE
Games don't start when running Wayland

### ISSUE THREAD

**Issue by ajshell1** [luxtorpeda-dev/luxtorpeda#57]
**Describe the bug**
None of the games I've tested that Luxtorpeda supports will launch on Wayland. The "Play" icon in the Steam client just goes almost instantly from "cancel" to "play" 

**To Reproduce**
Attempt to launch any game with Luxtorpeda set as the compatibility tool in a Wayland compositor.

**Expected behaviour**
The game would launch normally, as would happen on an X.org window manager.

**Screenshots**

**Additional context**
I'm currently using Void Linux with Sway. I'm using Luxtorpeda 24, although I'm certain that an older version of Luxtorpeda worked fine in Sway. I can also confirm that everything works fine on i3. In addition, it seems like whatever is going wrong is happening VERY early on. For example, I tried launching GTA3 with Luxtorpeda in Sway to no success. I logged out of Sway and started an i3 session, launched steam and then started GTA3, where the pop-up that informed me that reVC has an unknown license. So it wasn't even getting to that point in Wayland.

Also, I KNOW that I have XWayland installed and running. I also tried this with Wayfire with identical results.

Please let me know if there's anything more I can do to help you fix this issue.

**Comment by d10sfan** [comment]
Can you provide logs? That would be where you launch steam in terminal try and launch a game and then provide the output.

It sounds like the zenity prompt is failing which is the license pop-up you mentioned. We are using the steam provided zenity

**Comment by ajshell1** [comment]
This is really strange. It works FINE whenever I launch Steam from the command line, but it doesn't work fine when I launch steam normally.

I'm closing this issue, as I think it's likely that I'm launching steam incorrectly. Somehow.
