### ISSUE TITLE
Can't download engine

### ISSUE THREAD

**Issue by hsorsa** [luxtorpeda-dev/luxtorpeda#74]
I've installed Luxtorpeda according to instructions. Steam recognizes it as a compatibility layer, but when I try to run any game I get an error. Screenshot of terminal with error attached.

I've tried with multiple games, always same problem. Any ideas?

https://nebo.shorsa.info/index.php/s/9jiSMJTYSrfnfze

I'm attaching terminal log.
[luxtorpeda problem.txt](https://github.com/luxtorpeda-dev/luxtorpeda/files/6850801/luxtorpeda.problem.txt)

Sorry if there is any info missing. This is my first github post :D

**Comment by d10sfan** [comment]
I don't see an error anywhere in there. Is that the entire log?

What does the ~/.cache/luxtorpeda directory look like? Also, what does the game directory look like?

**Comment by hsorsa** [comment]
Dana 20.07.2021 21:32, d10sfan je napisao(la):

> I don't see an error anywhere in there. Is that the entire log?
> 
> What does the ~/.cache/luxtorpeda directory look like? Also, what does 
> the game directory look like?
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].

Yes, that's the entire log from starting the steam to game not running. 
It ends like the when i press play.

I'm sending you screenshots of both folders

-- 

_Srdačan pozdrav! Best regrads!_

_Hrvoje Šorša_
_www.shorsa.info_
***@***.***_
_+385 92 195 8505_

Links:
------
[1] 
https://github.com/luxtorpeda-dev/luxtorpeda/issues/74#issuecomment-883641696
[2]

**Comment by hsorsa** [comment]
![cache](https://user-images.githubusercontent.com/87722960/126385280-59dc7c58-d3fd-4822-aed6-c17531322930.png)
![game folder](https://user-images.githubusercontent.com/87722960/126385292-df6feb9f-4b8e-400f-8d51-02ac22ae643d.png)

**Comment by d10sfan** [comment]
Is this working now?

**Comment by hsorsa** [comment]
No. It remains the same. The luxtorepda version is luxtorpeda-25. Should I try with the older version? Sorry for later reply. It was late in my timezone.

[the same.txt](https://github.com/luxtorpeda-dev/luxtorpeda/files/6854377/the.same.txt)

**Comment by d10sfan** [comment]
I see, I thought you had solved it since you closed it. And no, that version should be fine.

It looks like you may be having some internet issues, by the dns issues error that showed up in that log. Did you try clearing your ~/.cache/luxtorpeda folder like above?

**Comment by hsorsa** [comment]
I've tried to clear ~/.cache/luxtorpeda and no changes. When I try to open the link https://github.com/luxtorpeda-dev/packages/releases/download/re3-1/ in browser i get "page not found". Is this normal?

**Comment by d10sfan** [comment]
Yes, but try downloading this: https://github.com/luxtorpeda-dev/packages/releases/download/re3-1/re3-12100-1.tar.xz

**Comment by hsorsa** [comment]
Download works like a charm...

**Comment by d10sfan** [comment]
Ok, what is in the ~/.cache/luxtorpeda directory?

**Comment by hsorsa** [comment]
Download from browser works normal, when I try in luxtorpeda the result is the same.

packages.json is the only file in ~/.cache/luxtorpeda directory.

**Comment by d10sfan** [comment]
Interesting, it looks like it's having issues downloading the files. The one log you sent had a reference to a download error of the hash, which could indicate some intermittent network issues. Could you try a few times and see if it's able to download?

Also, you could also try putting the manually downloaded file in the cache directory manually, in ~/.cache/luxtorpeda/appid/ for example for re3, replacing appid with the steam app id. That'll cause it to skip the download and just attempt to extract and run it.

**Comment by hsorsa** [comment]
> Interesting, it looks like it's having issues downloading the files. The one log you sent had a reference to a download error of the hash, which could indicate some intermittent network issues. Could you try a few times and see if it's able to download?
> 
> Also, you could also try putting the manually downloaded file in the cache directory manually, in ~/.cache/luxtorpeda/appid/ for example for re3, replacing appid with the steam app id. That'll cause it to skip the download and just attempt to extract and run it.

First part, the same. I've even tried uninstalling Steam, deleting all possible data. Installing it and again the same.

Then I've tried the second part. Downloaded the files, put them in cache folder and it installed like a charm, works great. I don't know  if anybody else had a similar problem, but maybe you can add option when installing engine to find the (downloaded) file manually. Like some sort of fail-safe. Just an idea.

Thank you for your help and assistance.

**Comment by d10sfan** [comment]
Interesting, do you have any sort of proxies or other unique network configuration? It's possible that the downloader isn't seeing those settings, leading to this issue.

**Comment by hsorsa** [comment]
> 
> 
> Interesting, do you have any sort of proxies or other unique network configuration? It's possible that the downloader isn't seeing those settings, leading to this issue.

I'e tried download over multiple networks and the result is always the same. Maybe something in my distro settings? KDE neon, runnig kernel 5.8? Also, out of curiosity, yesterday I've downloaded again "Jedi Knight II: Jedi Outcast" and tried Luxtorpeda. The result is the same problem - and the same workaround works.

**Comment by d10sfan** [comment]
> > Interesting, do you have any sort of proxies or other unique network configuration? It's possible that the downloader isn't seeing those settings, leading to this issue.
> 
> I'e tried download over multiple networks and the result is always the same. Maybe something in my distro settings? KDE neon, runnig kernel 5.8? Also, out of curiosity, yesterday I've downloaded again "Jedi Knight II: Jedi Outcast" and tried Luxtorpeda. The result is the same problem - and the same workaround works.

Not sure, we've had people in many distros and environments try this out and haven't encountered this from what I remember. I've never used Neon though, although can't think of anything that could contribute. It's possible you have some proxy settings or other network requirements that the download tool isn't seeing. 

Does a command line curl request work?

**Comment by d10sfan** [comment]
Closing in favor of https://github.com/luxtorpeda-dev/luxtorpeda/issues/75
