### ISSUE TITLE
Fresh install of Luxtorpeda 30 on OpenSUSE Tumbleweed fails at "Download Progress".

### ISSUE THREAD

**Issue by DigitalArcanist** [luxtorpeda-dev/luxtorpeda#82]
**Describe the bug**
Fairly recent system install of Tumbleweed, Steam, and Luxtorpeda 30.  Attempting to run games will bring up the prompts to choose engine and default, but when it gets to the Download stage, it halts with an error in the log:
`thread 'main' panicked at 'failed to update disable cancel progress: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/dialog.rs:362:39`

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Fresh OpenSUSE Tumbleweed (Currently at VERSION="20210810")
2. Install Steam
3. Installed Luxtorpeda 30 as per the instructions
4. Set "The Ultimate Doom" (appid 2280) to use Luxtorpeda (or other, this is what I was using)
5. Run game, select engine, I choose "no" to set as default
6. "Download Progress" window appears, but never progresses.

**Expected behaviour**
Should download needed components.

**Screenshots**
n/a

**Additional context**
Worked with d10sfan via Discord, who solved this in seconds.  Generated the following log:
`Starting app 2280
>>> Adding process 3402 for game ID 2280
GameAction [AppID 2280, ActionID 1] : LaunchApp changed task to WaitingGameWindow with ""
GameAction [AppID 2280, ActionID 1] : LaunchApp changed task to Completed with ""
ERROR: ld.so: object '/home/houn/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/houn/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
>>> Adding process 3407 for game ID 2280
update_packages_json. found hash: 23ccc2e8063324e911d2431e8d252bdc11dfcfb7
update_packages_json. found hash and remote hash: 23ccc2e8063324e911d2431e8d252bdc11dfcfb7 23ccc2e8063324e911d2431e8d252bdc11dfcfb7
creating: "/run/user/1000/luxtorpeda/2280.pid"
steam_app_id: "2280"
original command: ["/home/houn/.local/share/Steam/steamapps/common/Ultimate Doom/rerelease/DOOM.exe"]
working dir: Ok("/home/houn/.local/share/Steam/steamapps/common/Ultimate Doom")
tool dir: "/home/houn/.local/share/Steam/compatibilitytools.d/luxtorpeda"
user_packages_file not found
user_packages_file not found
showing engine choices
active_dialog_command. active_dialog_command_str: "default"
active_dialog_command. current_desktop: "KDE"
active_dialog_command. current desktop of kde found, kdialog found at "/usr/bin/kdialog"
engine choice: "gzdoom"
active_dialog_command. active_dialog_command_str: "default"
active_dialog_command. current_desktop: "KDE"
active_dialog_command. current desktop of kde found, kdialog found at "/usr/bin/kdialog"
default engine choice denied
engine choice complete
active_dialog_command. active_dialog_command_str: "default"
active_dialog_command. current_desktop: "KDE"
active_dialog_command. current desktop of kde found, kdialog found at "/usr/bin/kdialog"
progress_command  ["--geometry", "600x200", "--title", "Download Progress", "--progressbar", "Downloading...", "100"]
progress_disable_cancel_command ["org.kde.kdialog-3524", "/ProgressDialog", "showCancelButton", "false"]
thread 'main' panicked at 'failed to update disable cancel progress: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/dialog.rs:362:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
dropping: "/run/user/1000/luxtorpeda/2280.pid"
Installing breakpad exception handler for appid(steam)/version(1628721164)
Installing breakpad exception handler for appid(steam)/version(1628721164)`

d10sfan quickly identified that my system was missing qdbus, which is provided by libqt4 in Tumbleweed.  This was not installed in what I am fairly certain was a default KDE desktop install.  Added the library, and all was well.

d10sfan mentioned potentially adding a check for the existence of qdbus first, and/or falling back to zenity.

**Comment by d10sfan** [comment]
This should be fixed in luxtorpeda-31 (https://github.com/luxtorpeda-dev/luxtorpeda/commit/06045e6851c87d7fc0eaac0e07312b0f72c4ed4b)

Thanks for the report
